# Generated by Django 3.2.4 on 2021-06-04 12:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('shelf_life', models.IntegerField()),
                ('state', models.CharField(choices=[('freeze', 'freeze'), ('cold', 'cold')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MyIngredientInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_date', models.DateField(default=datetime.date.today)),
                ('quantity', models.IntegerField()),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='Refrigerator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredients', models.ManyToManyField(through='recipes.MyIngredientInfo', to='recipes.Ingredient')),
            ],
        ),
        migrations.AddField(
            model_name='myingredientinfo',
            name='refrigerator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.refrigerator'),
        ),
    ]
